### ISSUE TITLE
Deparallelize tensor parallelism

### ISSUE THREAD

**Issue by xrsrke** [xrsrke/pipegoose#11]
Convert a pippegoose's checkpoint [[link]](https://github.com/xrsrke/pipegoose/blob/db7598773806c4c0afeef1e6ce0b7119df92a5c9/pipegoose/nn/utils.py#L26) format to Hugging Face format

`pytorch_model_tp_{tp_rank}_pp_{pp_rank}.bin`

**Comment by xrsrke** [comment]
@ChufanSuki Yes, we do need it. Although we load `transformers`, but we split each one across GPUs during training [[link]](https://github.com/xrsrke/pipegoose/blob/3bcc83dac79b4dbba45286d7c3d66473b9cce9a2/pipegoose/nn/tensor_parallel/parallelizer.py#L125C9-L125C9), so each GPU only holds a portion of the weight. So we need to merge those weights back to the original format (is there any other way around this?). What you like to take this task. I will assign it to you. Feel free to ask me anything along the way.

**Comment by ChufanSuki** [comment]
I'm happy to take this task. I'll come back as soon as I manage to finish this.

**Comment by xrsrke** [comment]
@ChufanSuki sup. How is it going? This task is now a high priority. Can you get it done in the next week, or we will assign someone else? Thanks.

**Comment by 3outeille** [comment]
@xrsrke alright I'll take a look before fixing TP
