### ISSUE TITLE
Checkpointing

### ISSUE THREAD

**Issue by xrsrke** [xrsrke/pipegoose#24]
Save model during training.

**Comment by ChufanSuki** [comment]
I think I'll try to do this in this weekend.

**Comment by xrsrke** [comment]
> Do we follow the API with [olso](https://github.com/EleutherAI/oslo/blob/d7c4e32e766a99cc9d56533bc090570360dc8b2a/oslo/torch/utils/extensions.py#L37)

We don't.

@ChufanSuki Thank you. I think I already wrote this in this [link](https://github.com/xrsrke/pipegoose/blob/db7598773806c4c0afeef1e6ce0b7119df92a5c9/pipegoose/nn/utils.py#L26). It seems like duplication. But we need someone to convert the format to the Hugging Face format. Would you like to work on that

**Comment by ChufanSuki** [comment]
Sure. I’m not sure do we need convert the format to the 🤗 format since pipegoose already use 🤗 transformer.

**Comment by xrsrke** [comment]
@ChufanSuki I move the convo of pushing a parallelized model to the correspond issue. This one is duplication. Please check it here [[link]](https://github.com/xrsrke/pipegoose/issues/11). Thank you.
